<?php

echo "<!DOCTYPE html>\n";
echo "<html>\n";
echo "  <head>\n";
echo "    <meta charset=\"utf-8\">\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
echo "\n";
echo "    <title>Confirmation Page</title>\n";
echo "\n";
echo "    <!-- Styles -->\n";
echo "  <link rel=\"stylesheet\" href=\"css/common.css\">\n";
echo "  <link rel=\"stylesheet\" href=\"css/grid.css\">\n";
echo "  <link rel=\"stylesheet\" href=\"css/theme.css\">\n";
echo "    <!-- Fonts -->\n";
echo "    <link href=\"https://fonts.googleapis.com/css?family=Montserrat\" rel=\"stylesheet\">\n";
echo "    <link href=\"https://fonts.googleapis.com/css?family=Oswald\" rel=\"stylesheet\">\n";
echo "    <script src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\n";
echo "     <script src=\"js/main.js\"></script>\n";
echo "  </head>\n";
echo "\n";
echo "  <body>\n";
echo "\n";
echo "\n";
echo "      <input type=\"checkbox\" id=\"nav-menu\" class=\"hidden\">\n";
echo "      <label for=\"nav-menu\">≡</label>\n";
echo "      <!-- nav.nav.flex-none.nav-pills>ul>li*3>a[href=#]>{Link} -->\n";
echo "       <div class=\"navigation\">\n";
echo "      <nav class=\"navigation-left\">\n";
echo "        <ul>\n";
echo "          <li><a href=\"http://go-roxy.com/aau/wnm608/m07/productlist.html\">Online Store</a></li>\n";
echo "          <il><a href=\"#\">About Lula's</a></il>\n";
echo "          <il><a href=\"#\">Location</a></il>\n";
echo "        </ul>\n";
echo "    </nav>\n";
echo "      <div class=\"navigation-center\">\n";
echo "            <a href=\"http://go-roxy.com/aau/wnm608/m07/productlist.html\"><img src=\"images/logo.png\" alt=\"\" width=100%></a>\n";
echo "      </div>\n";
echo "      <div class=\"navigation-right\">\n";
echo "        <a href=\"#\"><img src=\"images/shopping-bag.png\" alt=\"\"></a>\n";
echo "        <button class=\"login-btn\" href=\"#\">Login</button>\n";
echo "      </div>\n";
echo "      </div>\n";
echo "\n";
echo "        </header>\n";
echo "   <div class=\"ccontainer\">\n";
echo "    <h1>Lula's Chocolaterie Order #2HQVX-W6GW</h1>\n";
echo "    <p>Thank you for your Chocolaterie order!\n";
echo "If you have any questions at all or problems with your order, please email us at contact@lulaschocolaterie.com.</p>\n";
echo "    <hr>\n";
echo "\n";
echo "    <h1>Order Information</h1>\n";
echo "    <hr>\n";
echo "    <p>Billed To:<br>\n";
echo "Darnell K. Landry<br>\n";
echo "1321 Chapel Street\n";
echo "Sugar Land, TX 77478<br>\n";
echo "281-665-0269<br>\n";
echo "Order Number: 2HQVX-W6GW<br>\n";
echo "Payment Method: Visa ****</p>\n";
echo " \n";
echo "\n";
echo "    <label for=\"email\"><b>Email</b></label>\n";
echo "    <input type=\"text\" placeholder=\"Enter Email\" name=\"email\" required>\n";
echo "\n";
echo "   \n";
echo "    <button type=\"submit\" class=\"registerbtn\">Sent Confirmation Email</button>\n";
echo "  </div>\n";
echo "  \n";
echo "\n";
echo "</form>\n";
echo " </body>";

?>