<?php

echo "<!DOCTYPE html>\n";
echo "<html>\n";
echo "  <head>\n";
echo "    <meta charset=\"utf-8\">\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
echo "\n";
echo "    <title>Purchase Page</title>\n";
echo "\n";
echo "    <!-- Styles -->\n";
echo "    <link rel=\"stylesheet\" href=\"css/common.css\">\n";
echo "    <link rel=\"stylesheet\" href=\"css/theme.css\">\n";
echo "\n";
echo "    <!-- Fonts -->\n";
echo "    <script src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\n";
echo "     <script src=\"js/main.js\"></script>\n";
echo "  </head>\n";
echo "   <div class=\"navigation\">\n";
echo "      <div class=\"navigation-left\">\n";
echo "        <a href=\"#\">Online Store</a>\n";
echo "        <a href=\"#\">About Lula's</a>\n";
echo "        <a href=\"#\">Location</a>\n";
echo "      </div>\n";
echo "      <div class=\"navigation-center\">\n";
echo "            <a href=\"http://go-roxy.com/aau/wnm608/m08/productlist.php\"><img src=\"images/logo.png\" alt=\"\" width=100%></a>\n";
echo "      </div>\n";
echo "      <div class=\"navigation-right\">\n";
echo "        <a href=\"#\"><img src=\"images/shopping-bag.png\" alt=\"\"></a>\n";
echo "        <button class=\"login-btn\" href=\"#\">Login</button>\n";
echo "      </div>\n";
echo "      <hr>\n";
echo "    </div>\n";
echo "\n";
echo "  <div class=\"cart\">\n";
echo "<div class=\"pwrapper\">\n";
echo "    <div class=\"pcontainer\">\n";
echo "        <form action=\"\">\n";
echo "            <h1>\n";
echo "                <i class=\"fas fa-shipping-fast\"></i> Shipping Details\n";
echo "            </h1>\n";
echo "            <div class=\"name\">\n";
echo "                <div>\n";
echo "                    <label for=\"f-name\">First</label>\n";
echo "                    <input type=\"text\" name=\"f-name\">\n";
echo "                </div>\n";
echo "                <div>\n";
echo "                    <label for=\"l-name\">Last</label>\n";
echo "                    <input type=\"text\" name=\"l-name\">\n";
echo "                </div>\n";
echo "            </div>\n";
echo "            <div class=\"street\">\n";
echo "                <label for=\"name\">Street</label>\n";
echo "                <input type=\"text\" name=\"address\">\n";
echo "            </div>\n";
echo "            <div class=\"address-info\">\n";
echo "                <div>\n";
echo "                    <label for=\"city\">City</label>\n";
echo "                    <input type=\"text\" name=\"city\">\n";
echo "                </div>\n";
echo "                <div>\n";
echo "                    <label for=\"state\">State</label>\n";
echo "                    <input type=\"text\" name=\"state\">\n";
echo "                </div>\n";
echo "                <div>\n";
echo "                    <label for=\"zip\">Zip</label>\n";
echo "                    <input type=\"text\" name=\"zip\">\n";
echo "                </div>\n";
echo "            </div>\n";
echo "            <h1>\n";
echo "                <i class=\"far fa-credit-card\"></i> Payment Information\n";
echo "            </h1>\n";
echo "            <div class=\"cc-num\">\n";
echo "                <label for=\"card-num\">Credit Card No.</label>\n";
echo "                <input type=\"text\" name=\"card-num\">\n";
echo "            </div>\n";
echo "            <div class=\"cc-info\">\n";
echo "                <div>\n";
echo "                    <label for=\"card-num\">Exp</label>\n";
echo "                    <input type=\"text\" name=\"expire\">\n";
echo "                </div>\n";
echo "                <div>\n";
echo "                    <label for=\"card-num\">CCV</label>\n";
echo "                    <input type=\"text\" name=\"security\">\n";
echo "                </div>\n";
echo "            </div>\n";
echo "     \n";
echo "               <a href=\"http://go-roxy.com/aau/wnm608/m08/confirmation.php\" class=\"btn continue\" >PURCHASE</a>\n";
echo "                <a href=\"http://go-roxy.com/aau/wnm608/m08/cartpage.php\" class=\"btn continue\" >Back To Cart</a>\n";
echo "  </div>\n";
echo "            </div>\n";
echo "        </form>\n";
echo "    </div>\n";
echo "</div>\n";
echo "</div>\n";
echo "</body>\n";
echo "</html>\n";

?>