<?php

echo "<!DOCTYPE html>\n";
echo "<html>\n";
echo "  <head>\n";
echo "    <meta charset=\"utf-8\">\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
echo "\n";
echo "    <title>Cart Page</title>\n";
echo "\n";
echo "    <!-- Styles -->\n";
echo "  <link rel=\"stylesheet\" href=\"css/cartpage.css\">\n";
echo "    <link rel=\"stylesheet\" href=\"css/common.css\">\n";
echo "    <link rel=\"stylesheet\" href=\"css/theme.css\">\n";
echo "\n";
echo "    <!-- Fonts -->\n";
echo "    <script src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\n";
echo "     <script src=\"js/main.js\"></script>\n";
echo "  </head>\n";
echo "   <div class=\"navigation\">\n";
echo "      <div class=\"navigation-left\">\n";
echo "        <a href=\"#\">Online Store</a>\n";
echo "        <a href=\"#\">About Lula's</a>\n";
echo "        <a href=\"#\">Location</a>\n";
echo "      </div>\n";
echo "      <div class=\"navigation-center\">\n";
echo "          <a href=\"http://go-roxy.com/aau/wnm608/m08/productlist.php\"><img src=\"images/logo.png\" alt=\"\" width=100%></a>\n";
echo "      </div>\n";
echo "      <div class=\"navigation-right\">\n";
echo "        <a href=\"#\"><img src=\"images/shopping-bag.png\" alt=\"\"></a>\n";
echo "        <button class=\"login-btn\" href=\"#\">Login</button>\n";
echo "      </div>\n";
echo "      <hr>\n";
echo "    </div>\n";
echo "\n";
echo "<div class=\"wrap cf\">\n";
echo "  <div class=\"heading cf\">\n";
echo "    <h1>My Cart</h1>\n";
echo "    <a href=\"http://go-roxy.com/aau/wnm608/m08/productlist.php\" class=\"continue\">Continue Shopping</a>\n";
echo "  </div>\n";
echo "  <div class=\"cart\">\n";
echo "\n";
echo "    <ul class=\"cartWrap\">\n";
echo "      <li class=\"items odd\">\n";
echo "        \n";
echo "    <div class=\"infoWrap\"> \n";
echo "        <div class=\"cartSection\">\n";
echo "          <p class=\"itemNumber\">#Cho-Dark-010</p>\n";
echo "          <h3>Passion Fruit</h3>\n";
echo "        \n";
echo "           <p> <input type=\"text\"  class=\"qty\" placeholder=\"3\"/> x $5.00</p>\n";
echo "        \n";
echo "          <p class=\"stockStatus\"> In Stock</p>\n";
echo "        </div>  \n";
echo "    \n";
echo "        \n";
echo "        <div class=\"prodTotal cartSection\">\n";
echo "          <p>$15.00</p>\n";
echo "        </div>\n";
echo "              <div class=\"cartSection removeWrap\">\n";
echo "           <a href=\"#\" class=\"remove\">x</a>\n";
echo "        </div>\n";
echo "      </div>\n";
echo "      </li>\n";
echo "      <li class=\"items even\">\n";
echo "        \n";
echo "       <div class=\"infoWrap\"> \n";
echo "        <div class=\"cartSection\">\n";
echo "          <p class=\"itemNumber\">#Cho-Milk-002</p>\n";
echo "          <h3>Dark Pistachio</h3>\n";
echo "        \n";
echo "           <p> <input type=\"text\"  class=\"qty\" placeholder=\"3\"/> x $5.00</p>\n";
echo "        \n";
echo "          <p class=\"stockStatus\"> In Stock</p>\n";
echo "        </div>  \n";
echo "        \n";
echo "        <div class=\"prodTotal cartSection\">\n";
echo "          <p>$15.00</p>\n";
echo "        </div>\n";
echo "    \n";
echo "            <div class=\"cartSection removeWrap\">\n";
echo "           <a href=\"#\" class=\"remove\">x</a>\n";
echo "        </div>\n";
echo "         </div>\n";
echo "         <div class=\"special\"><div class=\"specialContent\">Free gift with purchase!, gift wrap, etc!!</div></div>\n";
echo "      </li>\n";
echo "      \n";
echo "      \n";
echo "      <!--<li class=\"items even\">Item 2</li>-->\n";
echo " \n";
echo "    </ul>\n";
echo "  </div>\n";
echo "  \n";
echo "  <div class=\"promoCode\"><label for=\"promo\">Have A Promo Code?</label><input type=\"text\" name=\"promo\" placholder=\"Enter Code\" />\n";
echo "  <a href=\"#\" class=\"btn\"></a></div>\n";
echo "  \n";
echo "  <div class=\"subtotal cf\">\n";
echo "    <ul>\n";
echo "      <li class=\"totalRow\"><span class=\"label\">Subtotal</span><span class=\"value\">$35.00</span></li>\n";
echo "      \n";
echo "          <li class=\"totalRow\"><span class=\"label\">Shipping</span><span class=\"value\">$5.00</span></li>\n";
echo "      \n";
echo "            <li class=\"totalRow\"><span class=\"label\">Tax</span><span class=\"value\">$4.00</span></li>\n";
echo "            <li class=\"totalRow final\"><span class=\"label\">Total</span><span class=\"value\">$44.00</span></li>\n";
echo "      <li class=\"totalRow\"><a href=\"http://go-roxy.com/aau/wnm608/m08/purchasepage.php\" class=\"btn checkout\">Checkout</a></li>\n";
echo "    </ul>\n";
echo "  </div>";

?>