<?php

echo "<head>\n";
echo "    <meta charset=\"utf-8\">\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
echo "\n";
echo "    <title>Landing Page</title>\n";
echo "\n";
echo "    <!-- Styles -->\n";
echo "    <link rel=\"stylesheet\" href=\"css/common.css\">\n";
echo "    <link rel=\"stylesheet\" href=\"css/theme.css\">\n";
echo "\n";
echo "    <script src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\n";
echo "     <script src=\"js/main.js\"></script>\n";
echo "  </head>\n";
echo "\n";
echo "  <body>\n";
echo "  \n";
echo "   <div class=\"css-slider-wrapper\">\n";
echo "      <input type=\"radio\" name=\"slider\" class=\"slide-radio1\" checked id=\"slider_1\">\n";
echo "      <input type=\"radio\" name=\"slider\" class=\"slide-radio2\" id=\"slider_2\">\n";
echo "      <input type=\"radio\" name=\"slider\" class=\"slide-radio3\" id=\"slider_3\">\n";
echo "      <input type=\"radio\" name=\"slider\" class=\"slide-radio4\" id=\"slider_4\">\n";
echo "\n";
echo "      <!-- Slider Pagination -->\n";
echo "      <div class=\"slider-pagination\">\n";
echo "        <label for=\"slider_1\" class=\"page1\"></label>\n";
echo "        <label for=\"slider_2\" class=\"page2\"></label>\n";
echo "        <label for=\"slider_3\" class=\"page3\"></label>\n";
echo "        <label for=\"slider_4\" class=\"page4\"></label>\n";
echo "      </div>\n";
echo "\n";
echo "      <!-- Slider #1 -->\n";
echo "      <div class=\"slider slide-1\">\n";
echo "        <img src=\"images/slide1.jpg\" alt=\"\">\n";
echo "        <div class=\"slider-content\">\n";
echo "          <h4>Seasonal Flavors</h4>\n";
echo "          <h2>EARL GREY</h2>\n";
echo "          <a href=\"http://go-roxy.com/aau/wnm608/m08/sp.php\">\n";
echo "          <button type=\"button\" class=\"buy-now-btn\" name=\"button\">$5</button></a>\n";
echo "          <br>\n";
echo "          <br>\n";
echo "          <a href=\"http://go-roxy.com/aau/wnm608/m08/main.php\">\n";
echo "          <button type=\"button\" class=\"Enter-now-btn\" name=\"button\">Enter</button></a>\n";
echo "        </div>\n";
echo "        <div class=\"number-pagination\">\n";
echo "          <span>1</span>\n";
echo "        </div>\n";
echo "      </div>\n";
echo "\n";
echo "      <!-- Slider #2 -->\n";
echo "      <div class=\"slider slide-2\">\n";
echo "        <img src=\"images/slide2.jpg\" alt=\"\">\n";
echo "        <div class=\"slider-content\">\n";
echo "          <h4>New Product</h4>\n";
echo "          <h2>DARK CHOCOLATE TRUFFLE</h2>\n";
echo "          <a href=\"http://go-roxy.com/aau/wnm608/m08/sp.php\">\n";
echo "          <button type=\"button\" class=\"buy-now-btn\" name=\"button\">$5</button></a>\n";
echo "          <br>\n";
echo "          <br>\n";
echo "          <a href=\"http://go-roxy.com/aau/wnm608/m08/main.php\">\n";
echo "          <button type=\"button\" class=\"Enter-now-btn\" name=\"button\">Enter</button></a>\n";
echo "        </div>\n";
echo "        <div class=\"number-pagination\">\n";
echo "          <span>2</span>\n";
echo "        </div>\n";
echo "      </div>\n";
echo "\n";
echo "      <!-- Slider #3 -->\n";
echo "      <div class=\"slider slide-3\">\n";
echo "        <img src=\"images/slide3.jpg\" alt=\"\">\n";
echo "        <div class=\"slider-content\">\n";
echo "          <h4>Best Seller</h4>\n";
echo "          <h2>Coconut Pyramid</h2>\n";
echo "         <a href=\"http://go-roxy.com/aau/wnm608/m08/sp.php\">\n";
echo "          <button type=\"button\" class=\"buy-now-btn\" name=\"button\">$5</button></a>\n";
echo "          <br>\n";
echo "          <br>\n";
echo "          <a href=\"http://go-roxy.com/aau/wnm608/m08/main.php\">\n";
echo "          <button type=\"button\" class=\"Enter-now-btn\" name=\"button\">Enter</button></a>\n";
echo "        <div class=\"number-pagination\">\n";
echo "          <span>3</span>\n";
echo "        </div>\n";
echo "      </div>\n";
echo "\n";
echo "      <!-- Slider #4 -->\n";
echo "      <div class=\"slider slide-4\">\n";
echo "        <img src=\"images/slide4.jpg\" alt=\"\">\n";
echo "        <div class=\"slider-content\">\n";
echo "          <h4>Fruit</h4>\n";
echo "          <h2>Passion Fruit</h2>\n";
echo "        <a href=\"http://go-roxy.com/aau/wnm608/m07/sp.html\">\n";
echo "          <button type=\"button\" class=\"buy-now-btn\" name=\"button\">$5</button></a>\n";
echo "          <br>\n";
echo "          <br>\n";
echo "           <a href=\"http://go-roxy.com/aau/wnm608/m07/main.html\">\n";
echo "          <button type=\"button\" class=\"Enter-now-btn\" name=\"button\">Enter</button></a>\n";
echo "        <div class=\"number-pagination\">\n";
echo "          <span>4</span>\n";
echo "        </div>\n";
echo "      </div>\n";
echo "    </div>\n";
echo "  </body>\n";
echo "\n";
echo "</html>";

?>