<?php

echo "<!DOCTYPE html>\n";
echo "<html>\n";
echo "  <head>\n";
echo "    <meta charset=\"utf-8\">\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
echo "\n";
echo "    <title>Main page</title>\n";
echo "\n";
echo "    <!-- Styles -->\n";
echo "    <link rel=\"stylesheet\" href=\"css/common.css\">\n";
echo "    <link rel=\"stylesheet\" href=\"css/theme.css\">\n";
echo "      <link rel=\"stylesheet\" href=\"css/grid.css\">\n";
echo "\n";
echo "    <script src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\n";
echo "     <script src=\"js/main.js\"></script>\n";
echo "      <meta name=\"robots\" content=\"noindex,follow\" >\n";
echo "  </head>\n";
echo "\n";
echo "  <body>\n";
echo "    <div class=\"navigation\">\n";
echo "      <div class=\"navigation-left\">\n";
echo "        <a href=\"http://go-roxy.com/aau/wnm608/m08/productlist.php\">Online Store</a>\n";
echo "        <a href=\"#\">About Lula's</a>\n";
echo "        <a href=\"#\">Location</a>\n";
echo "      </div>\n";
echo "      <div class=\"navigation-center\">\n";
echo "        <a href=\"http://go-roxy.com/aau/wnm608/m08/productlist.php\"><img src=\"images/logo.png\" alt=\"\" width=100%></a>\n";
echo "      </div>\n";
echo "      <div class=\"navigation-right\">\n";
echo "        <a href=\"#\"><img src=\"images/shopping-bag.png\" alt=\"\"></a>\n";
echo "        <button class=\"login-btn\" href=\"\">Login</button>\n";
echo "      </div>\n";
echo "    </div>\n";
echo "  \n";
echo "  <div id=\"home-top\">\n";
echo "        <div class=\"mcontainer\">\n";
echo "          <div class=\"six columns\">\n";
echo "            <img src=\"images/product4.jpg\" alt=\"\" width=100%>\n";
echo "          </div>\n";
echo "          <div class=\"ten columns \">\n";
echo "            <h4>Featured Chocolate</h4> \n";
echo "            <div class=\"sep-left\"></div> \n";
echo "            <div class=\"sub-left\">Seven Days Without Chocolate Makes One Week</div> \n";
echo "            <p>Lula's Rosé chocolate infused with rosé wine! This is the hottest product of the summer! It's rosé season, so sit back, pour a glass, and take a bite of the sweetest new sensation of the year.</p>\n";
echo "          <div class=\"sixteen columns\">\n";
echo "            <div class=\"sep-wrap\"></div>\n";
echo "          </div>\n";
echo "        </div>\n";
echo "      </div>\n";
echo "\n";
echo "    <div id=\"about\">\n";
echo "      <div class=\"mcontainer\">\n";
echo "        <div class=\"sixteen columns padding-bottom\">\n";
echo "          <h4>Receive a $20 Bonus Card to Lula's!</h4> \n";
echo "          <div class=\"sep-center\"></div> \n";
echo "          <p>For a limited time receive a $20 Bonus eGift Card to Lula's Chocolaterie for every $100 spent in gift cards at any of our locations. Bonus eGifts valid until January 31, 2020.</p>\n";
echo "        </div>\n";
echo "        ";

?>
