<?php

echo "<!DOCTYPE html>\n";
echo "<html>\n";
echo "  <head>\n";
echo "    <meta charset=\"utf-8\">\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
echo "\n";
echo "    <title>Product List Page</title>\n";
echo "\n";
echo "    <!-- Styles -->\n";
echo "  <link rel=\"stylesheet\" href=\"css/common.css\">\n";
echo "  <link rel=\"stylesheet\" href=\"css/grid.css\">\n";
echo "  <link rel=\"stylesheet\" href=\"css/theme.css\">\n";
echo "    <!-- Fonts -->\n";
echo "    <script src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\n";
echo "     <script src=\"js/main.js\"></script>\n";
echo "  </head>\n";
echo "\n";
echo "  <body>\n";
echo "     <!-- Navigation -->\n";
echo "    <div class=\"navigation\">\n";
echo "      <div class=\"navigation-left\">\n";
echo "        <a href=\"http://go-roxy.com/aau/wnm608/m08/productlist.php\">Online Store</a>\n";
echo "        <a href=\"#\">About Lula's</a>\n";
echo "        <a href=\"#\">Location</a>\n";
echo "      </div>\n";
echo "      <div class=\"navigation-center\">\n";
echo "        <img src=\"images/logo.png\" alt=\"\" width=100%>\n";
echo "      </div>\n";
echo "      <div class=\"navigation-right\">\n";
echo "        <a href=\"#\"><img src=\"images/shopping-bag.png\" alt=\"\"></a>\n";
echo "        <button class=\"login-btn\" href=\"#\">Login</button>\n";
echo "      </div>\n";
echo "      <hr>\n";
echo "    </div>\n";
echo "    <nav class=\"product-filter col-xs-12 col-sm-6 col-lg-3\">\n";
echo "\n";
echo "  <div class=\"sort col-xs-12 col-sm-6 col-lg-3\">\n";
echo "\n";
echo "    <div class=\"collection-sort col-xs-12 col-sm-6 col-lg-3\">\n";
echo "      <label>Filter by:</label>\n";
echo "      <select>\n";
echo "        <option value=\"/\">Caramels</option>\n";
echo "        <option value=\"/\">Fruit</option>\n";
echo "        <option value=\"/\">Dark Chocolate</option>\n";
echo "        <option value=\"/\">Nut</option>\n";
echo "      </select>\n";
echo "    </div>\n";
echo "\n";
echo "    <div class=\"collection-sort col-xs-12 col-sm-6 col-lg-3\">\n";
echo "      <label>Sort by:</label>\n";
echo "      <select>\n";
echo "        <option value=\"/\">Best Selling</option>\n";
echo "        <option value=\"/\">Price Low to High</option>\n";
echo "        <option value=\"/\">Price High to Low</option>\n";
echo "      </select>\n";
echo "    </div>\n";
echo "\n";
echo "  </div>\n";
echo "\n";
echo "</nav>\n";
echo "\n";
echo " <div id=\"product-list\">\n";
echo "  <div class=\"product\">\n";
echo "    <div class=\"img\"><a href=\"http://go-roxy.com/aau/wnm608/m08/sp.php\"><img src=\"images/product1.jpg\"></div>\n";
echo "    <h3 class=\"title\">Coconut lime</h3></a>\n";
echo "    <div class=\"name\">A crisp refreshing lime coconut filling in a dark chocolate shell.</div></div>\n";
echo "\n";
echo "  <div class=\"product\">\n";
echo "    <div class=\"img\"><a href=\"http://go-roxy.com/aau/wnm608/m08/sp.php\"><img src=\"images/product2.jpg\"></div>\n";
echo "    <h4 class=\"title\">Lanvender</h4></a>\n";
echo "    <div class=\"name\">This luxurious chocolate features a 59% cacao content with notes of wine, fruit, nuts, and oak.\n";
echo "Infused with the delicious flavors of lavender essence and blueberries.</div></div>\n";
echo "  <div class=\"product\">\n";
echo "  <div class=\"img\"><a href=\"http://go-roxy.com/aau/wnm608/m08/sp.php\"><img src=\"images/product3.jpg\"></div>\n";
echo "    <h3 class=\"title\">Pistachio</h3></a>\n";
echo "    <div class=\"name\">Unique combination of fine chocolate and premium Turkish pistachios. </div></div>\n";
echo "\n";
echo "  <div class=\"product\">\n";
echo "   <div class=\"img\"><a href=\"http://go-roxy.com/aau/wnm608/m08/sp.php\"><img src=\"images/product4.jpg\"></div>\n";
echo "    <h3 class=\"title\">Rosé</h3></a>\n";
echo "    <div class=\"name\">Lula's Rosé chocolate infused with rosé wine! This is the hottest product of the summer! It's rosé season, so sit back, pour a glass, and take a bite of the sweetest new sensation of the year.</div></div>\n";
echo "\n";
echo "  <div class=\"product\">\n";
echo "    <div class=\"img\"><a href=\"http://go-roxy.com/aau/wnm608/m08/sp.php\"><img src=\"images/product5.jpg\"></div>\n";
echo "    <h3 class=\"title\">Salted Caramel</h3></a>\n";
echo "    <div class=\"name\">Rich dark chocolate wrapped around decadent caramel,Sprinkled with coarse sea salt</div>\n";
echo "  </div>\n";
echo "  <div class=\"product\">\n";
echo "    <div class=\"img\"><a href=\"http://go-roxy.com/aau/wnm608/m08/sp.php\"><img src=\"images/product6.jpg\"></div>\n";
echo "    <h3 class=\"title\">Champagne</h3></a>\n";
echo "    <div class=\"name\">Dark Ganache Blended with a touch of champagne.</div>\n";
echo "  </div>\n";
echo "  <div class=\"product\">\n";
echo "    <div class=\"img\"><a href=\"http://go-roxy.com/aau/wnm608/m08/sp.php\"><img src=\"images/product7.jpg\"></div>\n";
echo "    <h3 class=\"title\">Cappuccino</h3></a>\n";
echo "    <div class=\"name\">Luxurious milk chocolate infused with coffee</div></div>\n";
echo "\n";
echo "  <div class=\"product\">\n";
echo "    <div class=\"img\"><a href=\"http://go-roxy.com/aau/wnm608/m08/sp.php\"><img src=\"images/product8.jpg\"></div>\n";
echo "    <h4 class=\"title\">Matcha</h4></a>\n";
echo "    <div class=\"name\">Matcha powder is blended in white chocolate. Enjoy deep and rich matcha aroma and smooth texture of chocolate</div></div>\n";
echo "  <div class=\"product\">\n";
echo "  <div class=\"img\"><a href=\"http://go-roxy.com/aau/wnm608/m08/sp.php\"><img src=\"images/product9.jpg\"></div>\n";
echo "    <h3 class=\"title\">Strawberry</h3></a>\n";
echo "    <div class=\"name\">White chocolate mixed with powdered strawberries and three kinds of dried fruit, almond puffs, and a touch of banana essence. 12 pieces per box. </div></div>\n";
echo "\n";
echo "  <div class=\"product\">\n";
echo "   <div class=\"img\"><a href=\"http://go-roxy.com/aau/wnm608/m08/sp.php\"><img src=\"images/product10.jpg\"></div>\n";
echo "    <h3 class=\"title\">Dark Rum</h3></a>\n";
echo "    <div class=\"name\">Rich,dark chocolate infused with spiced rum.</div></div>\n";
echo "\n";
echo "  <div class=\"product\">\n";
echo "    <div class=\"img\"><a href=\"http://go-roxy.com/aau/wnm608/m08/sp.php\"><img src=\"images/product11.jpg\"></div>\n";
echo "    <h3 class=\"title\">Orange</h3></a>\n";
echo "    <div class=\"name\">Oranges covered in dark Chocolate.</div>\n";
echo "  </div>\n";
echo "    <div class=\"product\">\n";
echo "    <div class=\"img\"><a href=\"http://go-roxy.com/aau/wnm608/m08/sp.php\"><img src=\"images/product12.jpg\"></div>\n";
echo "    <h3 class=\"title\">Hazelnut</h3></a>\n";
echo "    <div class=\"name\">Rich hazelnut praline whipped with creamy milk chocolate.</div>\n";
echo "  </div>\n";
echo "\n";
echo "</div>\n";
echo "</div>\n";
echo "\n";

?>