<?php

echo "<!DOCTYPE html>\n";
echo "<html>\n";
echo "  <head>\n";
echo "    <meta charset=\"utf-8\">\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
echo "\n";
echo "    <title>Single Product Page</title>\n";
echo "\n";
echo "    <!-- Styles -->\n";
echo "  <link rel=\"stylesheet\" href=\"css/common.css\">\n";
echo "  <link rel=\"stylesheet\" href=\"css/grid.css\">\n";
echo "  <link rel=\"stylesheet\" href=\"css/theme.css\">\n";
echo "    <!-- Fonts -->\n";
echo "    <link href=\"https://fonts.googleapis.com/css?family=Montserrat\" rel=\"stylesheet\">\n";
echo "    <link href=\"https://fonts.googleapis.com/css?family=Oswald\" rel=\"stylesheet\">\n";
echo "    <script src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\n";
echo "     <script src=\"js/sp.js\"></script>\n";
echo "\n";
echo "  </head>\n";
echo "\n";
echo "  <body>\n";
echo "     <!-- Navigation -->\n";
echo "    <div class=\"navigation\">\n";
echo "      <div class=\"navigation-left\">\n";
echo "        <a href=\"#\">Online Store</a>\n";
echo "        <a href=\"#\">About Lula's</a>\n";
echo "        <a href=\"#\">Location</a>\n";
echo "      </div>\n";
echo "      <div class=\"navigation-center\">\n";
echo "          <a href=\"http://go-roxy.com/aau/wnm608/m08/productlist.php\"><img src=\"images/logo.png\" alt=\"\" width=100%></a>\n";
echo "      </div>\n";
echo "      <div class=\"navigation-right\">\n";
echo "        <a href=\"#\"><img src=\"images/shopping-bag.png\" alt=\"\"></a>\n";
echo "        <button class=\"login-btn\" href=\"#\">Login</button>\n";
echo "      </div>\n";
echo "      <hr>\n";
echo "    </div>\n";
echo "\n";
echo "   <main class=\"singleproduct_container\">\n";
echo "\n";
echo "      <!-- Left Column / Headphones Image -->\n";
echo "      <div class=\"left-column col-sm-6\">\n";
echo "        <img data-image=\"black\" src=\"images/singleproduct2.jpg\" alt=\"\" >\n";
echo "        <img data-image=\"blue\" src=\"images/singleproduct1.jpg\" alt=\"\" >\n";
echo "        <img data-image=\"red\" class=\"active\" src=\"images/singleproduct.jpg\" alt=\"\">\n";
echo "      </div>\n";
echo "\n";
echo "\n";
echo "      <!-- Right Column -->\n";
echo "      <div class=\"right-column col-sm-6\">\n";
echo "\n";
echo "        <!-- Product Description -->\n";
echo "        <div class=\"single_product-description\">\n";
echo "          <span>Chocolate</span>\n";
echo "          <br>\n";
echo "          <h1>Passion Fruit</h1>\n";
echo "          <p>The Passion Fruit Chocolates are incredibly smooth and rich, sweet and tart. They’re just lovely.</p>\n";
echo "        </div>\n";
echo "\n";
echo "        <!-- Product Configuration -->\n";
echo "        <div class=\"product-configuration\">\n";
echo "\n";
echo "          <!-- Product Color -->\n";
echo "          <div class=\"product-color\">\n";
echo "            <span>Milk or Dark</span>\n";
echo "\n";
echo "            <div class=\"color-choose\">\n";
echo "              <div>\n";
echo "                <input data-image=\"red\" type=\"radio\" id=\"red\" name=\"color\" value=\"red\" checked>\n";
echo "                <label for=\"red\"><span></span></label>\n";
echo "              </div>\n";
echo "              <div>\n";
echo "                <input data-image=\"blue\" type=\"radio\" id=\"blue\" name=\"color\" value=\"blue\">\n";
echo "                <label for=\"blue\"><span></span></label>\n";
echo "              </div>\n";
echo "              <div>\n";
echo "                <input data-image=\"black\" type=\"radio\" id=\"black\" name=\"color\" value=\"black\">\n";
echo "                <label for=\"black\"><span></span></label>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "\n";
echo "          </div>\n";
echo "              <div class=\"cable-config col-xs-12 col-sm-6 col-lg-3\">\n";
echo "            <span>Size</span>\n";
echo "\n";
echo "            <div class=\"cable-choose col-xs-12 col-sm-6 col-lg-3\">\n";
echo "              <button>9-piece</button>\n";
echo "              <button>12-piece</button>\n";
echo "              <button>20-piece</button>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "        </div>\n";
echo "\n";
echo "\n";
echo "        <!-- Product Pricing -->\n";
echo "        <div class=\"single_product-price\">\n";
echo "          <span>$5</span>\n";
echo "          <a href=\"http://go-roxy.com/aau/wnm608/m08/cartpage.php\" class=\"cart-btn\">Add to cart</a>\n";
echo "        </div>\n";
echo "      </div>\n";
echo "    </main>\n";
echo "  </body>\n";
echo "</html>";

?>